URL: "https://gdqstats.com"
title: GDQStats.com

author: Alexander Frisch

languageCode: "en-us"
languageLang: "en"

disableKinds: ["RSS", "taxonomy", "taxonomyTerm", "sitemap", "404"]

enableRobotsTXT: true

params:
  current_event: Flame Fatales
  current_event_short_hand: flamefatales
  current_event_year: 2024

  # Set to "true" to disable home page and switch to flipclock as homepage
  countdown_enabled: false

  # The time that the flipclock counts down to
  event_start: "2022-08-18T09:30:00.00-08:00"

  previous_events:
    - name: SGDQ
      year: 2024

    - name: AGDQ
      year: 2024

    - name: SGDQ
      year: 2023

    - name: AGDQ
      year: 2023

    - name: AGDQ
      year: 2022

    - name: SGDQ
      year: 2021

    - name: AGDQ
      year: 2021

    - name: SGDQ
      year: 2020

    - name: AGDQ
      year: 2020

    - name: SGDQ
      year: 2019

    - name: AGDQ
      year: 2019

    - name: SGDQ
      year: 2018

    - name: AGDQ
      year: 2018

    - name: SGDQ
      year: 2017

    - name: AGDQ
      year: 2017

    - name: SGDQ
      year: 2016

  description: >
    Data Visualizations for GamesDoneQuick Marathons
